import type { HomeVersion } from "@/lib/home";
import { arena } from "@/theme/arena";

/** MIT UI 키트의 시각 언어만 가져온다. 패키지는 설치하지 않는다. */
export type HomeKit = {
  id: HomeVersion;
  name: string;
  source: string;
  license: string;
  note: string;
  bg: string;
  surface: string;
  surface2: string;
  text: string;
  muted: string;
  line: string;
  primary: string;
  primaryFg: string;
  ghost: string;
  ghostFg: string;
  ghostLine: string;
  live: string;
  liveFg: string;
  /** 브랜드·선택 강조 (없으면 primary) */
  accent?: string;
  /** 히어로 분위기 원·띠 */
  glow?: string;
  radius: number;
  heroRadius: number;
  scoreSize: number;
  statusBar: "dark" | "light";
};

const ZINC_LIGHT: Omit<HomeKit, "id" | "name" | "source" | "note" | "scoreSize" | "heroRadius" | "radius"> = {
  license: "MIT",
  bg: "#FAFAFA",
  surface: "#FFFFFF",
  surface2: "#F4F4F5",
  text: "#09090B",
  muted: "#71717A",
  line: "#E4E4E7",
  primary: "#18181B",
  primaryFg: "#FAFAFA",
  ghost: "#FFFFFF",
  ghostFg: "#18181B",
  ghostLine: "#E4E4E7",
  live: "#DC2626",
  liveFg: "#FFFFFF",
  statusBar: "dark",
};

export const HOME_KITS: Record<HomeVersion, HomeKit> = {
  v1: {
    ...ZINC_LIGHT,
    id: "v1",
    name: "shadcn/ui",
    source: "https://ui.shadcn.com",
    note: "zinc 라이트 · 보더 카드 · 하단 sticky CTA",
    radius: 8,
    heroRadius: 8,
    scoreSize: 28,
  },
  v2: {
    id: "v2",
    name: "daisyUI",
    source: "https://daisyui.com",
    license: "MIT",
    note: "light 테마 · 라운드 히어로 · primary 액션",
    bg: "#F2F2F2",
    surface: "#FFFFFF",
    surface2: "#EDE9FE",
    text: "#1F2937",
    muted: "#6B7280",
    line: "#E5E7EB",
    primary: "#570DF8",
    primaryFg: "#FFFFFF",
    ghost: "#EDE9FE",
    ghostFg: "#570DF8",
    ghostLine: "#DDD6FE",
    live: "#F87272",
    liveFg: "#1F2937",
    radius: 16,
    heroRadius: 24,
    scoreSize: 22,
    statusBar: "dark",
  },
  v3: {
    id: "v3",
    name: "Eva Dark",
    source: "https://akveo.github.io/react-native-ui-kitten/",
    license: "MIT",
    note: "UI Kitten 다크 · 라이브 스코어 핀",
    bg: "#151A30",
    surface: "#222B45",
    surface2: "#1A2138",
    text: "#FFFFFF",
    muted: "#8F9BB3",
    line: "#2E3A59",
    primary: "#3366FF",
    primaryFg: "#FFFFFF",
    ghost: "#2E3A59",
    ghostFg: "#FFFFFF",
    ghostLine: "#2E3A59",
    live: "#FF3D71",
    liveFg: "#FFFFFF",
    radius: 12,
    heroRadius: 16,
    scoreSize: 48,
    statusBar: "light",
  },
  h1: {
    id: "h1",
    name: "브랜드 허브",
    source: "docs/home-brand-sport-hub-wire.html",
    license: "MIT",
    note: "Arena T&M · 전역 theme/arena.ts 와 동기",
    bg: arena.bg,
    surface: arena.surface,
    surface2: arena.surface2,
    text: arena.text,
    muted: arena.muted,
    line: arena.line,
    primary: arena.primary,
    primaryFg: arena.primaryFg,
    ghost: arena.ghost,
    ghostFg: arena.ghostFg,
    ghostLine: arena.ghostLine,
    live: arena.live,
    liveFg: arena.liveFg,
    accent: arena.primary,
    glow: arena.glow,
    radius: arena.radius,
    heroRadius: arena.heroRadius,
    scoreSize: 36,
    statusBar: "light",
  },
  h2: {
    id: "h2",
    name: "라이브 우선",
    source: "GameChanger + Scoreholio",
    license: "구성 참고",
    note: "오늘 코트 · 라이브 핀 먼저 · 종목 칩",
    bg: "#0F1419",
    surface: "#1A222D",
    surface2: "#243041",
    text: "#F5F7FA",
    muted: "#9AA4B2",
    line: "#2E3A4A",
    primary: "#3D8BFF",
    primaryFg: "#FFFFFF",
    ghost: "#243041",
    ghostFg: "#F5F7FA",
    ghostLine: "#3A4A5C",
    live: "#FF5A4A",
    liveFg: "#FFFFFF",
    radius: 12,
    heroRadius: 16,
    scoreSize: 44,
    statusBar: "light",
  },
  h3: {
    id: "h3",
    name: "종목 모자이크",
    source: "써포츠식 종목 진입",
    license: "구성 참고",
    note: "종목이 히어로 · 선택 카드에서 CTA",
    bg: "#F7F5F0",
    surface: "#FFFFFF",
    surface2: "#EFEBE3",
    text: "#1C1917",
    muted: "#78716C",
    line: "#E7E5E4",
    primary: "#0F766E",
    primaryFg: "#FFFFFF",
    ghost: "#FFFFFF",
    ghostFg: "#0F766E",
    ghostLine: "#99F6E4",
    live: "#C2410C",
    liveFg: "#FFFFFF",
    radius: 14,
    heroRadius: 18,
    scoreSize: 24,
    statusBar: "dark",
  },
  h4: {
    id: "h4",
    name: "이중 진입",
    source: "NX League / Scoreholio",
    license: "구성 참고",
    note: "대회 운영 vs 빠른 친선 두 문",
    bg: "#F8FAFC",
    surface: "#FFFFFF",
    surface2: "#F1F5F9",
    text: "#0F172A",
    muted: "#64748B",
    line: "#E2E8F0",
    primary: "#1D4ED8",
    primaryFg: "#FFFFFF",
    ghost: "#EFF6FF",
    ghostFg: "#1D4ED8",
    ghostLine: "#BFDBFE",
    live: "#E11D48",
    liveFg: "#FFFFFF",
    radius: 14,
    heroRadius: 20,
    scoreSize: 28,
    statusBar: "dark",
  },
  h5: {
    id: "h5",
    name: "벤토 2026",
    source: "Bento + thumb-first · H1 Arena 팔레트",
    license: "구성 참고",
    note: "H1과 색 동일 · 레이아웃·썸존만 다름",
    bg: arena.bg,
    surface: arena.surface,
    surface2: arena.surface2,
    text: arena.text,
    muted: arena.muted,
    line: "transparent",
    primary: arena.primary,
    primaryFg: arena.primaryFg,
    ghost: arena.surface2,
    ghostFg: arena.text,
    ghostLine: arena.line,
    live: arena.live,
    liveFg: arena.liveFg,
    accent: arena.primary,
    glow: arena.glow,
    radius: 20,
    heroRadius: 24,
    scoreSize: 48,
    statusBar: "light",
  },
  h6: {
    id: "h6",
    name: "라이트 데스크",
    source: "Strava + Linear · 라이트 단일 액센트",
    license: "구성 참고",
    note: "흰 캔버스 · 펌프킨 오렌지 하나 · 피드형 · H1과 반대",
    bg: "#F7F6F4",
    surface: "#FFFFFF",
    surface2: "#EFEDEA",
    text: "#0E0E0E",
    muted: "#6B6B6B",
    line: "#E4E2DE",
    primary: "#FC4C02",
    primaryFg: "#FFFFFF",
    ghost: "#FFFFFF",
    ghostFg: "#0E0E0E",
    ghostLine: "#D8D5D0",
    live: "#FC4C02",
    liveFg: "#FFFFFF",
    accent: "#FC4C02",
    glow: "rgba(252, 76, 2, 0.12)",
    radius: 12,
    heroRadius: 16,
    scoreSize: 56,
    statusBar: "dark",
  },
  h7: {
    id: "h7",
    name: "브리즈 아레나",
    source: "H1 layout + fresh tone",
    license: "구성 참고",
    note: "H1과 동일 UX · 상쾌한 민트/스카이 톤",
    bg: "#EAF8F6",
    surface: "#FFFFFF",
    surface2: "#DDF3F0",
    text: "#073B4C",
    muted: "#4A6B74",
    line: "#C8E7E3",
    primary: "#10B981",
    primaryFg: "#FFFFFF",
    ghost: "#F3FFFC",
    ghostFg: "#075985",
    ghostLine: "#BFE8DF",
    live: "#0EA5E9",
    liveFg: "#FFFFFF",
    accent: "#06B6D4",
    glow: "rgba(6, 182, 212, 0.18)",
    radius: 12,
    heroRadius: 14,
    scoreSize: 36,
    statusBar: "dark",
  },
};
